server:
  port: 8090
spring:
  application:
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://81.70.45.13:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: "xiaoming"
      password: "Root@1234"
  redis:
    host: 81.70.45.13
    port: 6379
    password: root
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键生成策略
      id-type: ASSIGN_ID

reggie:
  path: /www/wwwroot/img/

logging:
  level:
    com.zeal: debug






